### ISSUE TITLE
Cannot steer right in browser on desktop

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#10]
As title, when running the game on a browser on a computer, the robot cannot steer right.

**Comment by jhird11** [comment]
Can't reproduce on Windows 10 chrome using the arrow keys. Anyone else has this issue?

**Comment by mhl787156** [comment]
Huh, maybe it's just my particular setup, something else is grabbing my 'D' key - maybe should also enable arrow keys

**Comment by mhl787156** [comment]
Yup I found vim for chrome was binding my D key - this is not an issue! Closing!
