### ISSUE TITLE
Transition between Tutorial and Mission 1

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#100]
@jhird11 @gabriellamiles, what is the plan for the transition between the missions? Is it triggered if the player goes into a particular area?

**Comment by jhird11** [comment]
When the player goes through the waterfall I believe. Should just be achieved by triggering load_enviroment when the robot enters the waterfall


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Mickey Li ***@***.***>
Sent: Monday, 14 June 2021, 11:38
To: FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game
Cc: Julian Hird; Mention
Subject: [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game] Transition between Tutorial and Mission 1 (#100)


@jhird11<https://github.com/jhird11> @gabriellamiles<https://github.com/gabriellamiles>, what is the plan for the transition between the missions? Is it triggered if the player goes into a particular area?

**Comment by mhl787156** [comment]
Okay... there's no waterfall yet in tutorial though? I'm guessing thats going to be in some other branch?

**Comment by jhird11** [comment]
Does the current tutorial level have any assets in what's so ever? I think they still need merging on top of each other

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mhl787156** [comment]
No, the tutorial still has the blue blocks? I think it needs a second pass anyhow if we're redoing the intro too

**Comment by jhird11** [comment]
Done! But mission 1 isn't finished yet
