### ISSUE TITLE
Add whisker textures to all interactable objects in the level

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#106]
Currently whisker only recognizes a select few objects (and displays the texture of a select few objects). We need to add textures ad descriptions to more objects

**Comment by jhird11** [comment]
Added placeholder textures for most objects some still remain eg. plants, yeti shorts

**Comment by jhird11** [comment]
I think this is done. More could be added but there's a good number of objects now
