### ISSUE TITLE
Missions not populated afterload

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#123]
Mission list doesn't populate for main mission after load

**Comment by jhird11** [comment]
I think this is something to do with the way missions are loaded. I tried to add some stuff so that the control panel UI is deleted when the robot is freed which made the overlay appear again . . Maybe one for you @mhl787156 ?

**Comment by mhl787156** [comment]
I believe this has been resoluved
