### ISSUE TITLE
Check mission 1 dialog

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#126]
This hasn't been reviewed and is full of errors

**Comment by gabriellamiles** [comment]
@mhl787156 @jhird11 The most recent pull request should resolve this I think? I've been through and proofread everything.

**Comment by mhl787156** [comment]
Yup this should now be complete, I have adjusted the dialog for the plants to make it clearer, as well as added an extra bit of dialog here and there. in v1.0.1
