### ISSUE TITLE
Improve heatmaps for levels

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#129]
These could do with tweaking

**Comment by mhl787156** [comment]
Improved heatmap for tutorial level: 
![image](https://user-images.githubusercontent.com/10742598/122618822-f46e5a80-d086-11eb-97a5-0fb9f6fa1851.png)

**Comment by mhl787156** [comment]
Also updated Mission 1 with more noise and a bit more diffusion (by liberal use of bluring and smudging!)
![MissionHeatmap](https://user-images.githubusercontent.com/10742598/122620244-5a101600-d08a-11eb-9332-d06e81fc2c51.jpg)
