### ISSUE TITLE
Lidar visualisation

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#13]
The current lidar visualisation is very sparse. 

I propose that we switch to a sprite based system e.g. https://kidscancode.org/godot_recipes/ui/minimap/

**Comment by jhird11** [comment]
I think the current system can work, but the robot must be represented via a sprite of some sort.

This goes with a larger question of whether the LIDAR stays in the global frame or the local frame. Ie. Will the little sprite in the middle showing which way you're pointing rotate. Or will the whole LIDAR reading rotate around a fixed arrow indicating the forward direction.

**Comment by mhl787156** [comment]
Agree to the robot sprite. I think the rest of the space does need to be filled in more though.

I think the original idea is for the robot to always be in the centre bottom, and that you get a cone of sensor readings fixed from the local frame. I think the point is we don't have anything from the global frame shown to the user. 
On that note we should play around with some of the parameters,  I think the sweep needs to be quicker with higher res probably

**Comment by Skyrah1** [comment]
Some new visual updates have been added to the LIDAR, including a couple of sprites representing where the robot is, on PR https://github.com/FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game/pull/39
