### ISSUE TITLE
Lidar readings aren't plotted relative to the robot

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#16]
The lidar works but the readings appear to plotted in global space, instead of relative to the robot. It means if you go too far away from the origin lidar readings are no longer plotted.

**Comment by kirstyaquilina** [comment]
Instead of rotating the laser, rotate the cast to vector:     
var point_laser = Vector3(max_range,0,0)
ray.set_cast_to(point_laser.rotated(Vector3(0,1,0),deg2rad(counter)))

However, the origin of the laser still looks off and needs to be fixed and weirder things happen when you try to move the robot.

**Comment by kirstyaquilina** [comment]
Also counter is set to 0 after it reaches 360 deg; it would be good to use the value of counter (modulus 360) rather than setting it to zero as otherwise the laser could be going in a different direction for a short while (e.g. 365 -> 0).

**Comment by jhird11** [comment]
Hi Kirsty, would you be happy to make these changes and submit them as a pull request? I think @blueicefrog (Pete) was also said he might look at them?

**Comment by jhird11** [comment]
Hi @kirstyaquilina and @blueicefrog, I've given @MihaiAnca13 this issue because he was looking for things to do but if either of you still wanted to contribute towards the LIDAR development let me know :)

**Comment by MihaiAnca13** [comment]
head_location = $LidarBody/Head.global_transform.origin

This should be updated in the process as well.

**Comment by MihaiAnca13** [comment]
@jhird11 I've just pushed some changes to the develop-fix-lidar branch. It's now working as intended thanks to @kirstyaquilina's comments. 

I think there's still work to be done for the occupancy map texture, but I haven't had time to look into it for now.

**Comment by jhird11** [comment]
Ah good stuff! I've just had a look and the weird spinning definitely seems to of been fixed, good job!

I just pushed a draft version of mission 1 onto the master branch to test the lidar in if you'd like to test its operation in a more realistic setting :)

**Comment by Skyrah1** [comment]
The LIDAR readings should now be updating relative to the robot on PR: https://github.com/FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game/pull/39
