### ISSUE TITLE
Temperature sensor hasn't been implemented yet

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#17]

**Comment by MihaiAnca13** [comment]
@hendrikE can you please write down the ideas you had over the weekend here?

**Comment by jhird11** [comment]
Temperature sensor stuff has now been uploaded to the temperature branch. But isn't functional yet.

A quick overview of how I think this was going to work:

Use generate_heatmap.py to generate an image representing temperatures across the map.

A thermometer (Assets/Thermometer.png) would then be filled up to represent the temperature.

**Comment by jhird11** [comment]
An update to this. Got a basic working sensor on the temperature branch (video [here](https://teams.microsoft.com/l/message/19:8c7b8f9b73fd4e2fa3706ceac6720338@thread.tacv2/1622101837048?tenantId=b2e47f30-cd7d-4a4e-a5da-b18cf1a4151b&groupId=ddbe1d95-cb8f-450e-abe9-a26dae896f77&parentMessageId=1622101837048&teamName=grp-FARSCOPE-UKRAS%20%20Festival%20of%20Robotics%20Event&channelName=Development%20Screenshots&createdTime=1622101837048)) Still needs integrating into the rest of the GUI

**Comment by jhird11** [comment]
Integrated into master with #34
