### ISSUE TITLE
Rethink whiskers

### ISSUE THREAD

**Issue by MihaiAnca13** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#18]
The rendered texture coming from the whiskers should include text showing what it bumped into and maybe some other attributes - right now its not particularly useful

**Comment by MihaiAnca13** [comment]
This could be achieved if the textures used are following a naming convention. Ex: name_texture.

**Comment by jhird11** [comment]
Yeah that works if the only information we want to display is the name. Perhaps a lookup table between the texture name and the item name + info would be more expandable?

**Comment by jhird11** [comment]
Objectives:
- Display name of sensed object
- Ability to display other fields 
- Scatch card effect

**Comment by MihaiAnca13** [comment]
A quick update (https://youtu.be/_I9BjB5BopY) and a question. I've added a sample rock texture just to play with. It currently doesn't resize it when displaying it in the control panel. There was also a bug, where the last texture was always displayed, so now I just show a blank white image instead.

I was trying two things:

- read texture data from a csv file - works
- display text on top of texture

I couldn't find a way to draw text on top of an image inside godot. There is a way to draw it on a canvas item, but I haven't had time to explore that for now. However, the problem is in linking the data from the csv file with the texture the whiskers come across. You can't read the name of the rigid body or the name of the texture, so I'm not sure how we could do it. I've saved the data from the csv file in a dictionary. Any ideas?

**Comment by mhl787156** [comment]
The resizing - make sure that code is in _process! 

Drawing text on top of image should just be using the Label node as a canvas node, really easy to add :) 

On the linking, if we gave each object a texture id from an enum, then the globals.gd can have a mapping from the enum to csv? Then the sensor essentially does a lookup based on the touched object texture_id? 

On that note we should have a fallback texture which displays like 'material not recognised' or something!

**Comment by mhl787156** [comment]
Also was having a think of what the UI might look like. Depending on whether you can get the location of the texture within the hitbox - then you can actually use it for navigation tasks! 
![WhatsApp Image 2021-05-19 at 11 54 37](https://user-images.githubusercontent.com/10742598/118801687-2f6b4b80-b899-11eb-810a-aa5ae795605a.jpeg)

**Comment by MihaiAnca13** [comment]
> The resizing - make sure that code is in _process!
> 
> Drawing text on top of image should just be using the Label node as a canvas node, really easy to add :)
> 
> On the linking, if we gave each object a texture id from an enum, then the globals.gd can have a mapping from the enum to csv? Then the sensor essentially does a lookup based on the touched object texture_id?
> 
> On that note we should have a fallback texture which displays like 'material not recognised' or something!

Good idea with the label! Makes it much easier.

How would you add that texture_id to the object? Do we need a custom class that extends RigidBody that has this extra id? How would we set it for each?

**Comment by MihaiAnca13** [comment]
> Also was having a think of what the UI might look like. Depending on whether you can get the location of the texture within the hitbox - then you can actually use it for navigation tasks!

Good idea. I'll have a look to see if it's possible.

**Comment by mhl787156** [comment]
Adding texture_id... hmm maybe there's something built in to help add parameters? Otherwise yeah, we would have one script where all does is `export texture_id` and attach that too anything we want the robot to have a texture interaction with? 
Other option is we create a new type of node called TextureRigidBody which includes an extra texture_id/other texture based information. Not sure how to do that tho!

**Comment by jhird11** [comment]
How many objects do we want to be detected by the tactile sensor? We could add a node within objects the tactile sensor interacts with which is like "tactile_info" which would contain the id. Then if the node isn't found then the tactile sensor doesn't sense that object?

**Comment by mhl787156** [comment]
Yeah thats also an option - very much depends on how many objects/ which objects! Might have to go to the design team on that..

**Comment by jhird11** [comment]
There's quite a few open questions in my mind about the remaining functionality that needs implementing to compete the puzzles. eg. How the tactile sensor is going to be used, how the temperature sensor is going to be used, whats our narrator guide/tooltip stuff going to work, how are objectives displayed.

**Comment by jhird11** [comment]
I've created issues for the dialogue and objective systems in #27 #28 and #29 

I think we need two bits of info from the game dev team a) a list of puzzles - to check our sensor functionality matches their expectations and b) a list of all the UI systems that are needed (for objectives dialogue etc.). I will send a message in teams :) 

I will post any info relating to the tactile sensor hear :)

**Comment by MihaiAnca13** [comment]
Quick update: https://youtu.be/U9DKDvsjXxk
I've added the label as you suggested and it's now using data from the csv file to display texture name. This is using the rigid body name, but can be swapped to texture_id later on. 

I haven't implemented the top bar depending on collision just yet and have no idea where to start with that scratch effect.

**Comment by jhird11** [comment]
Hi Mihai, it's looking good!

I thought the scratch card effect would consist of composting the texture being displayed with the frames of an animated overlay. I'm happy to try to implement this because I know you've got other tasks on your radar?

**Comment by MihaiAnca13** [comment]
Sorry for the late reply. Please feel free to have a go at it. I was away for the weekend and didn't have time to work on it.

I want to add what Mickey suggested with the top bar for collision, but then I'd like to have a go at LIDAR to see if I can fix it.

**Comment by jhird11** [comment]
That sounds good, let me know when you commit your changes so so I build on top of what you finish :)

**Comment by jhird11** [comment]
That sounds good. I don't think I'm entirely clear what @mhl787156 suggested but please do have a go at it :)

**Comment by mhl787156** [comment]
@MihaiAnca13 what information do you get from a collision detection volume? If what I suggested doesnt work, I'm happy to take other suggestions on giving a little more feedback then 'oh you've bumped into fern' haha 

@jhird11 essentially some feedback on where in physical space the texture is coming from. e.g. the whisker 'feels' a  couple of plants int front of it, so some dots pop up to show the relative location within the collision volume?

**Comment by jhird11** [comment]
Ah I see, I'll have a think. I think it depends how the puzzles have been designed around the tactile sensor as to what functionality is required.

**Comment by jhird11** [comment]
I've implemented a basic animation for when the whiskers enter an object. I also neatened up the UI a bit as well. See the video [here](https://teams.microsoft.com/l/message/19:8c7b8f9b73fd4e2fa3706ceac6720338@thread.tacv2/1621981853674?tenantId=b2e47f30-cd7d-4a4e-a5da-b18cf1a4151b&groupId=ddbe1d95-cb8f-450e-abe9-a26dae896f77&parentMessageId=1621981853674&teamName=grp-FARSCOPE-UKRAS%20%20Festival%20of%20Robotics%20Event&channelName=Development%20Screenshots&createdTime=1621981853674): 

I had to do the UI stuff in a bit of a hacky way, seems like all the sensor code should be refactored. @hendrikE will be posting some code relating to the temperature sensor so hopefully we can come up a with a unifying framework for all sensors :)

**Comment by MihaiAnca13** [comment]
@jhird11 it looks very good! I had a quick look at how you fixed the texture scaling issue. It looks like right now it's hardcoded, so we need to make sure it looks good on all screen types.

@mhl787156 You only get a signal for when an object enters/leaves the area. I was thinking I can create an "Area" object for each whisker and display it as dots as you suggested. Do you think that will be okay?

**Comment by mhl787156** [comment]
@jhird11 looks good love the animation! Maybe we should have a conversation about how we're doing screen scaling - it should be case of using the scaling grids right? 
@MihaiAnca13 hmmm what about something like 6 tiny floating cubes in a line inside the area? Then if one of them gets triggered, we can show a little 'hit' sprite for that cube?

**Comment by jhird11** [comment]
Not sure what you mean by scaling grids. Godot features a number containers for GUI elements which if configured correctly should handle the scaling for us.

The only weird thing about that animation is the AnimatedSprite isn't a standard GUI element (it's from 2D game engine side) but it does scale with the window size but doesn't have the usual UI controls (anchors etc). I probably should re-impliment it as either a texture rectangle that sits on top of the display texture or composite the animation texture and the material texture within the WhiskerSensor script. The latter is probably  neater. And would remove a lot of the hacky stuff I did to get the current stuff working. I think I'll wait until we re-do the UI in general though before attempting this

**Comment by MihaiAnca13** [comment]
- no more csv file
- place label and TextureRect as child
OR
- do it with the script and add those to a group

**Comment by jhird11** [comment]
Completed by adding custom node to objects. Feature merged
