### ISSUE TITLE
Stop robot bouncing and flipping over 

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#21]
The robot is very bouncy and currently gets stuck when it flips over

**Comment by archie1983** [comment]
Issue fixed with commits: 
592a83065f7b8846c5838bab517221a48f149dc9
7fffa98ff283a7f63d30a1493e6af91657d26fd8
8b64c1c37b7d8ef52074f9235943d6c41ce30bc8
