### ISSUE TITLE
Deploy/Hosting the game publically

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#24]
We need to work out how to host this game on AWS (https://aws.amazon.com/)

**Comment by mhl787156** [comment]
Michael is happy to work out a way to fund this and #25

**Comment by jhird11** [comment]
I'm not really sure how this stuff works, do we know anyone who does? I assume Michael just wants "where do I click buy" info, so we need to work out where that button is.

**Comment by mhl787156** [comment]
I think it's more of a, lets set up an account linked to the Farscope credit card. 

It should just be start up a Amazon S3 server. Then doing #25 and pointing it at the public IP of the S3 server? There should be lots of online tutorials 

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Tutorials.WebServerDB.CreateWebServer.html 
https://docs.aws.amazon.com/efs/latest/ug/wt2-apache-web-server.html

No idea which one. We should ideally find somebody whose done this stuff before... I dont really know anyone either hmm

**Comment by mhl787156** [comment]
Update - Hopefully we can host on the BRL Website

**Comment by mhl787156** [comment]
This is now solved with money, currently hosting on https://fasrcope-outreach.co.uk
