### ISSUE TITLE
COME UP WITH A NAME FOR THE GAME

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#26]
As in the title!

**Comment by jhird11** [comment]
I'm happy to run a couple of rounds of polls to brain storm ideas for this?

**Comment by mhl787156** [comment]
New Name! 
RoC-Ex: Robotic Cave Explorer
Unearth the truth about what happened in cave system #0393
