### ISSUE TITLE
Dialogue system

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#28]
This would display dialogue triggered by the environment

**Comment by jhird11** [comment]
@mhl787156 was Utilities/Textbox.tscn your attempt at this? And did you want to continue this further?

From looking over it it seems we aleady have a way of queuing text and I like the way it animates. 

I think implimenting this would consist of creating a new type of object called "DialogTrigger.tscn" or soemthing simular which would be collision volume that the robot could pass through, but would still be able to detect that the robot had touched it using the body_entered method. The robot would need a method like .recievedialog(text) and then this method would emit a signal like emit_signal("dialog_recieved",text) to communicate with the GUI. The GUI can then queue the text on the Textbox object and then maybe store it somewhere else so players can look back through the dialogue? 

The object would export the text it was going to display so we could place multiple of them in the level and the text can be configured via the editor.

**Comment by mhl787156** [comment]
That was actually @MihaiAnca13 ! I was wondering how the dialogue would work, I wonder if Valentina had ideas about how it should be displayed to the user - the current textbox is wayyy too small anyway

Hmmm I think we should draw and discuss this somewhere. I think the collision trigger is definitely one way of doing it. Either way at this point it will be us highly scripting everything. On a usability note, I think we should get the designers to build a json/yaml whatever file with all of the dialogue, keys being dialogue ids which we can tie together with a particular trigger. 

The other option I suppose is in-game popups /cutscenes when you get close to a particular object (e.g. if you go close to the stream/ dark corridor) - this would work well with your DialogTrigger idea too. 

Sorry stream of conciousness! Then maybe the DialogTrigger containes a Dialog ID parameter. At initialisation it reads the dialog-config json and populates itself with the value of its given id. 

On a different note, maybe we should do some research onto how to best construct it - e.g. https://www.davidepesce.com/2020/01/27/godot-tutorial-14-npc-quest-dialogue/

**Comment by jhird11** [comment]
Yeah I agree having all the dialog in a single file would be good. Especially if different conditions can trigger the same dialog!

**Comment by jhird11** [comment]
I've done a test run of this on develop-dialog (video [here](https://teams.microsoft.com/l/message/19:8c7b8f9b73fd4e2fa3706ceac6720338@thread.tacv2/1622218064996?tenantId=b2e47f30-cd7d-4a4e-a5da-b18cf1a4151b&groupId=ddbe1d95-cb8f-450e-abe9-a26dae896f77&parentMessageId=1622218064996&teamName=grp-FARSCOPE-UKRAS%20%20Festival%20of%20Robotics%20Event&channelName=Development%20Screenshots&createdTime=1622218064996))
