### ISSUE TITLE
Locomotion method

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#33]
Opening an issue for discussing whether to change locomotion from car based to omnidirectional or tank driving based. 
Reason is that with car driving locomotion it might be easy to get stuck inside a cave environment. Also most robots these days will be tank steering. 
Difficulty is in displaying a tank driving UI/ controls on the screen. Is it possible to have single stick tank driving? 
E.g. joystick left/right rotates around axis, forward backwards on the stick drives forward or backward. You cannot yaw while going activlely moving. 

Other options might be preferable as well.

**Comment by jhird11** [comment]
I think I'd support tank controls if we can get them working. There is now a basic playable level curtesy of @weijiewong1991 so we can check how bad the current controls play

**Comment by Skyrah1** [comment]
There's an issue with the current implementation of tank controls where the player slides up the walls. Other than that, if we can get the player to stick to the floor we should be good

**Comment by mhl787156** [comment]
Also need to consider #11 #20 and #22 for if we want to change how the joystick works

**Comment by mhl787156** [comment]
Completed
