### ISSUE TITLE
Improve the temperature sensor to handle multiple heatmaps

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#35]
Currently the sensor uses a single heatmap across the entire map which might result in a very large texture for large maps.

If the temperature is mostly zero apart from a few places of interest we can use multiple heatmaps to represent these areas. 

The temperature sensor would need to check which heatmap the sensor is currently in and then read the temperature accordingly.

The calibration method would need to alterted so the sensor can register multiple heatmaps.

The get temperature method would need to check the sensor against all heatmaps and then get the texture coordinates as normal.

**Comment by jhird11** [comment]
This would be a nice to have as the current system works. Just a thought I'd had as I wrapping up implementation

**Comment by mhl787156** [comment]
This sounds like a good enhancement - although if the map becomes that large we probably need to split the map up first... 
Note temp sensor should stay at around 5 degrees probably - can add random noise to simulate random temperature variations outside of multiple heatmaps! It will be interesting to see the best way to locate a sensor heatmap in a particular location.

**Comment by mhl787156** [comment]
Background loading for reference: https://docs.godotengine.org/en/stable/tutorials/io/background_loading.html

**Comment by jhird11** [comment]
Ah so at the moment theres's a calibration body which can be moved around with texture on it. Hence it's fairly easy to place a single heatsource... but then if the heatmap contains multiple heat sources you need to get the distances in the texture correct. 

As I say I think the current system is clunky but it does work and if we only have a few heat sources it shouldn't be too bad, but if the heat sources need accurate positioning using multiple heatmaps makes sense.

**Comment by jhird11** [comment]
Gonna close this because what we have at the moment is workable
