### ISSUE TITLE
Starting Sequence Node

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#49]
There will need to be a starting sequence to take the player from the main menu to the control panel. This needs to be designed and implemented. Current thoughts are

1. MainMenu press start button
2. Bring into turned off computer mode - show dialog of background (maybe a picture of the mountain in the background)
3. Computer turns on - play turn on sounds, show computer turn on screen 
4. Control Panel turns on - Control Panel appears with sensors loading. sensors finish loading and play turned on sound
5. Into control panel. 

@LGVal do you think you could create some of the intermediate scenes? so a picture of a turned off laptop lid up, laptop lighting up. maybe others?

**Comment by jhird11** [comment]
This can be achieved using the tutorial_scripts.gd see tutorial branch

**Comment by jhird11** [comment]
Let's also not forget #30 

At the moment the tutorial script directly alters the sensor GUI elements. I think a clearer storyboard of what this would look like is needed before we script this.

**Comment by mhl787156** [comment]
I believe this is mostly completed, but in need of a bit of an update

**Comment by jhird11** [comment]
I don't think we've actually implemented the node that would do this. Atm it's all done through the dialog system.

Is there any update on the storyboard/ art for this?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mhl787156** [comment]
Yes there is, @gabriellamiles showed me some shots yeseterday of backgrounds Tbh steps 3 - 5 are essentially implemented in the curent build? 
We can move all of that into its own node? But if it works fine we can probably leave it...

Whatever we decide, I think getting this don is high priority.

I think what's being done in #99 should help out

**Comment by jhird11** [comment]
Integrated with #115
