### ISSUE TITLE
Integrate visual and scripted mission levels

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#50]
With Julians work on sorting out the scripting of the mission in #28 and objective system #27 we now need to script the missions. This will include scripting the objectives, the journal logs and the dialog. Refer to the mission plans in the Teams

**Comment by jhird11** [comment]
initial version on tutorial-script branch!

**Comment by mhl787156** [comment]
This is now complete
