### ISSUE TITLE
Robot has difficulty traversing Mission 1 cave 

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#57]
In particular two sections I've discovered from the tutorial script

![image](https://user-images.githubusercontent.com/47662879/120883871-9bf38380-c5d7-11eb-8e98-11b576f4ee52.png)

**Comment by mhl787156** [comment]
@a98-smith or @ADRSmith would you be able to have a look at this?

**Comment by jhird11** [comment]
Video evidence :) https://teams.microsoft.com/l/message/19:8c7b8f9b73fd4e2fa3706ceac6720338@thread.tacv2/1622879195015?tenantId=b2e47f30-cd7d-4a4e-a5da-b18cf1a4151b&groupId=ddbe1d95-cb8f-450e-abe9-a26dae896f77&parentMessageId=1622849291466&teamName=grp-FARSCOPE-UKRAS%20%20Festival%20of%20Robotics%20Event&channelName=Development%20Screenshots&createdTime=1622879195015

**Comment by Skyrah1** [comment]
Beyond the tutorial, the robot seems to have difficulty driving through tunnels in general. It might have to do with how narrow the tunnels are, so maybe it would be worth either making all the tunnels wider or scaling the whole level up?

**Comment by jhird11** [comment]
Yeah I agree. I think this fix is a combination of scaling up the cave and them changing the robot's collision box to be capsule so it doesn't catch on the cave mesh.

**Comment by jhird11** [comment]
While we're fixing this we should can tune the robot's speed a bit.

**Comment by gabriellamiles** [comment]
I've done some testing on the new mission 1 cave mesh and I think it's slightly better now. There are still some areas that are slightly narrower and reduce the robot's speed a bit, but nothing that results in it getting stuck.

**Comment by mhl787156** [comment]
At @jhird11 @gabriellamiles do we think this is fixed now? If so lets close thise issue

**Comment by jhird11** [comment]
I think this only applied to old map. I've had no trouble with the new one

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mhl787156** [comment]
Okay great, closing issue then!
