### ISSUE TITLE
Add Compass to indicate direction from North

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#65]
Suggestions here are to have a bar along the top of the screen showing N/E/S/W with additional subdivisions based on rotation from X (say) axis.

**Comment by jhird11** [comment]
@MihaiAnca13 would you be interested in implementing this? It's a bit of a stand alone task :) 
I think Alex mentioned the skyrim bar which was kinda cool. Could probably be done by shifting a repeated texture around maybe?

![image](https://user-images.githubusercontent.com/47662879/121030350-4c60b380-c7a1-11eb-9bd6-1b37a24d5991.png)

Let me know either way :) 

PS:
Also thanks for your work on the Whiskers! it was merged over the weekend and looks super sexy! I really like the dots flickering

**Comment by MihaiAnca13** [comment]
I'm happy to do it, but I will need your help with merging it with the master branch. I'm bound to have problems with the ControlPanel placement.

**Comment by mhl787156** [comment]
If you make it as its own scene, we can deal with placement later. We've finally figured out that its all about the anchors haha
