### ISSUE TITLE
Import new textures into the control panel UI

### ISSUE THREAD

**Issue by jhird11** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#72]
New textures are being made for the control panel lets remember to put them in! Will post when they're ready

**Comment by weijiewong1991** [comment]
I can put them in on the control_panel_improvement branch.

**Comment by jhird11** [comment]
Ah if you'd like. I tried to add them other day but I don't think they were square or the same size so it caused some issues. I asked valentina if she'd like to make them square but haven't heard anything back so far.

**Comment by weijiewong1991** [comment]
Just tried it and I see what you mean now. Personally I don't mind the gaps. I've changed the control panel background to a square version based on Valentina's new files.

**Comment by jhird11** [comment]
Great thanks! 
Yeah I don't mind some gaps I think its more that the top button clips the top of the screen, but wouldn't if the gaps were smaller. I'll leave this open and we can revisit the buttons if new textures are made or we have time to polish the existing ones

**Comment by weijiewong1991** [comment]
https://uob.sharepoint.com/teams/grp-FARSCOPE-UKRASFestivalofRoboticsEvent/Shared%20Documents/Game-a-thon%20Prototype%20Weekend%201/Menu%20and%20UI%20Design/Temporary/Square_icons.JPG

I rescaled all the icons, does it look better now?

**Comment by jhird11** [comment]
Looks alright to me!

Just checking are you working on the latest version that temperature sensor on left looks a little out of date?

**Comment by weijiewong1991** [comment]
I did not merge from master yet.

**Comment by jhird11** [comment]
Ah okay doke :)

**Comment by jhird11** [comment]
I think this is good enough
