### ISSUE TITLE
Initial Loading Screen

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#90]
The current loading screen takes a while and is completely blank, would be good to get a better screen! 

![image](https://user-images.githubusercontent.com/10742598/121395222-17dc2b80-c94a-11eb-8089-05198c60c929.png)

**Comment by gabriellamiles** [comment]
Is this something you want some artwork for? Or are you thinking a bit more basic?

**Comment by mhl787156** [comment]
I think we can go pretty basic for this - I was thinking the name (game logo?) of our game with all the institution logos on the bottom? BRL, UWE, UOB, ESPRC, UKRAS Robotics Festival and any others? Still needs creating though! 
I believe that we can upload a jpg and that will just display as splash screen? Need to look a bit more into it though

**Comment by mhl787156** [comment]
Solved by #105
